name: ClinicalTrialHealth
options:
  bundleIdPrefix: com.clinicaltrialcopilot
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  ClinicalTrialHealth:
    type: application
    platform: iOS
    sources:
      - ClinicalTrialHealth
    settings:
      base:
        INFOPLIST_FILE: ClinicalTrialHealth/Info.plist
        CODE_SIGN_ENTITLEMENTS: ClinicalTrialHealth/ClinicalTrialHealth.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.clinicaltrialcopilot.health
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
    entitlements:
      path: ClinicalTrialHealth/ClinicalTrialHealth.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access:
          - health-records
